services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consume-newUser-created-uat
    environment:
      RABBITMQ_HOST: rabbitDocker-uat
      RABBITMQ_USERNAME: sinqia
      RABBITMQ_PASSWORD: sinqia123
      RABBITMQ_PORT: 5672
      AWSSecretKey: "***"
      AWSAccessKey: "***"
    networks:
      - church-registration-uat_netchurchmanager

networks:
  church-registration-uat_netchurchmanager:
    external: true # Indica que a rede jรก existe no Docker